In [2]:
from mxnet import nd

In [8]:
x = nd.random.uniform(shape=(2,3))

In [10]:
a = x.asnumpy()
a

array([[ 0.59284461,  0.71518934,  0.84426576],
       [ 0.60276335,  0.85794562,  0.54488319]], dtype=float32)

In [11]:
nd.array(a)


[[ 0.59284461  0.71518934  0.84426576]
 [ 0.60276335  0.85794562  0.54488319]]
<NDArray 2x3 @cpu(0)>